/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaomakj_hellogcc_MuchJNIShow */

#ifndef _Included_com_xiaomakj_hellogcc_MuchJNIShow
#define _Included_com_xiaomakj_hellogcc_MuchJNIShow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaomakj_hellogcc_MuchJNIShow
 * Method:    muchShow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xiaomakj_hellogcc_MuchJNIShow_muchShow
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
