//
// Created by Administrator on 2018/8/3.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaomakj_hellogcc_MuchJNIShow */
#include <string.h>
#include <android/log.h>

#define LOGV(...) __android_log_print(ANDROID_LOG_VERBOSE, "com.droider.jnimethods", __VA_ARGS__)
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, "com.droider.jnimethods", __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, "com.droider.jnimethods", __VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, "com.droider.jnimethods", __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "com.droider.jnimethods", __VA_ARGS__)

#ifndef _Included_com_xiaomakj_hellogcc_MuchJNIShow
#define _Included_com_xiaomakj_hellogcc_MuchJNIShow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaomakj_hellogcc_MuchJNIShow
 * Method:    muchShow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xiaomakj_hellogcc_MuchJNIShow_muchShow
  (JNIEnv * env, jobject object, jint age){
    LOGD("string1");
    LOGD("string2 %s%d","Maqi",age);
  }

#ifdef __cplusplus
}
#endif
#endif
