/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaomakj_hellogcc_TestJniMethods */

#ifndef _Included_com_xiaomakj_hellogcc_TestJniMethods
#define _Included_com_xiaomakj_hellogcc_TestJniMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaomakj_hellogcc_TestJniMethods
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaomakj_hellogcc_TestJniMethods_test
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaomakj_hellogcc_TestJniMethods
 * Method:    nativeMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiaomakj_hellogcc_TestJniMethods_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
